"""first migrations

Revision ID: ae2b1b6c8fd0
Revises: 
Create Date: 2020-07-06 21:25:48.195352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2b1b6c8fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.String(length=32), nullable=False),
    sa.Column('carbs', sa.String(length=16), nullable=False),
    sa.Column('protein', sa.String(length=16), nullable=False),
    sa.Column('fat', sa.String(length=16), nullable=False),
    sa.Column('sodium', sa.String(length=16), nullable=False),
    sa.Column('sugar', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    op.drop_table('category')
    # ### end Alembic commands ###
